### ISSUE TITLE
'schema' folder to create dynamic schemas

### ISSUE THREAD

**Issue by jdnichollsc** [bjrmatos/sequelize-auto-import#2]
Hi my friend, thanks for this module! It's very useful, like magic! 👍 

What do you think about to create a **"schema"** folder to create multiples schemas using the same models?

For example => 
```
/path/to/models
├── user.js
├── schema
│   ├── product.js
│   └── contact.js
└── index.js
```

And in the **index.js**
```
var models = require('sequelize-auto-import')(sequelize, '/path/to/models', {
   schemas: ['company1', 'company2', 'company3']
});
```

And access the models in this way:
```
models.user
models.company1.product
models.company1.contact
models.company2.product
models.company2.contact
models.company3.product
models.company3.contact
```

Thanks in advance, Nicholls

**Comment by bjrmatos** [comment]
sure! seems like there is a good use case behind this option. PR welcome! if not, i will work on it in the end of the week.

**Comment by jdnichollsc** [comment]
Thanks! About the PR, let me check your code first :)

**Comment by jdnichollsc** [comment]
Hi @bjrmatos, sorry for my mistake, my changes in the pull request are working properly! 💯
